name: Build and Deploy with Docker

on:
  push:
    branches:
      - main #for prod
      - dev #for development

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/location-app:latest

      - name: Deploy with docker-compose (Local Runner)
        run: |
          set -e
          
          echo "Preparing ~/location-app..."
          mkdir -p ~/location-app
          
          echo "Copying docker-compose.yml..."
          cp docker-compose.yml ~/location-app/
          
          echo "Copying .env if exists..."
          if [ -f .env ]; then cp .env ~/location-app/; fi
          
          echo "Switching to deploy directory..."
          cd ~/location-app
          
          echo "Pulling latest image..."
          docker-compose pull
          
          echo "Running docker-compose up..."
          docker-compose up -d

      # This is show how to deploy to EC2 with security group (use dev branch)
      - name: Add MAIN's public IP to AWS security group
        if: github.ref == 'refs/heads/dev' #for main branch
        uses: sohelamin/aws-security-group-add-ip-action@master
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'eu-central-1'
          aws-security-group-id: ${{ secrets.AWS_SECURITY_GROUP_ID }}
          port: ${{ secrets.SSH_PORT }}
          to-port: '30'
          protocol: 'tcp'
          description: 'GitHub Action'

      - name: Copy docker-compose.yml to EC2
        if: github.ref == 'refs/heads/dev' #for main branch
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "docker-compose.yml"
          target: "~/location-app/docker-compose.yml"

      - name: Deploy to MAIN with docker-compose
        if: github.ref == 'refs/heads/dev'
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_USER: ${{ secrets.SSH_USERNAME }}
          SOURCE: |
            docker-compose.yml
          TARGET: "~/location-app"
          SCRIPT_BEFORE: |
            echo "Cleaning previous deploy..."
            rm -rf ~/location-app/*
          SCRIPT_AFTER: |
            echo "Running docker-compose..."
            cd ~/location-app
            docker-compose pull
            docker-compose up -d